name: Deploy
on: [push]
jobs:
  compile_cv_common:
    runs-on: ubuntu-latest
    name: Compile and deploy cv-common
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: docker build -t cv --build-arg target=common .
      - name: Run
        run: docker run -v $PWD/common:/CV/common -t cv
      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: common
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
