name: Deploy
on: [push]
jobs:
  compile_cv_common:
    runs-on: ubuntu-latest
    name: Compile & deploy all CVs
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create pdf folder
        run: mkdir pdf

      - name: Build CV-math
        run: docker build -t cv_math --build-arg target=math .
      - name: Run CV-math
        run: docker run -v $PWD/math:/CV/math -t cv_math
      - name: Collect CV-math.pdf
        run: cp math/CV-math.pdf pdf/CV-math.pdf

      - name: Build CV-it
        run: docker build -t cv_it --build-arg target=it .
      - name: Run CV-it
        run: docker run -v $PWD/it:/CV/it -t cv_it
      - name: Collect CV-it.pdf
        run: cp it/CV-it.pdf pdf/CV-it.pdf

      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: pdf
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
