name: Deploy
on: [push]
jobs:
  compile_cv_common:
    runs-on: ubuntu-latest
    name: Compile & deploy all CVs
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create pdf folder
        run: mkdir pdf
      - name: Build CV-common
        run: docker build -t cv_common --build-arg target=common .
      - name: Run CV-common
        run: docker run -v $PWD/common:/CV/common -t cv_common
      - name: Collect cv-common.pdf
        run: cp common/cv-common.pdf pdf/cv-common.pdf
      - name: Build CV-math
        run: docker build -t cv_math --build-arg target=math .
      - name: Run CV-math
        run: docker run -v $PWD/math:/CV/math -t cv_math
      - name: Collect cv-math.pdf
        run: cp math/cv-math.pdf pdf/cv-math.pdf
      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: pdf
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
