name: Deploy
on: [push]
jobs:
  compile_resume_docker:
    runs-on: ubuntu-latest
    name: Compile in docker and deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: docker build -t cv .
      - name: Run
        run: docker run -v $PWD/CV:/workdir/CV -t cv
      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: CV
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
